#!/usr/bin/env bash
#a Bash script that will display information about subdomains

subDomains=(www. lb-01. web-01. web-02.)

domainInfo () {
	for value in "${subDomains[@]}"; do
		dig "$value$1" | grep -A1 'ANSWER SECTION:' |
		awk 'NR==2{sub(/\..*$/, "", $1); print "The subdomain",$1, "is a", $4, "record and points to", $5}'
	done
}

if [ ! "$2" ]
then
	domainInfo "$1"
else
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' |
	awk 'NR==2{sub(/\..*$/, "", $1); print "The subdomain",$1, "is a", $4, "record and points to", $5}'
fi
