#!/usr/bin/env bash
#Install and configure HAproxy 

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get install -y haproxy


# Create a new HAProxy configuration file
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http_frontend
    bind *:80
    default_backend web_backend

backend web_backend
    balance roundrobin
    server web-01 54.86.225.115:80 check
    server web-02 54.198.34.163:80 check
EOT

# Restart HAProxy to apply changes
sudo systemctl restart haproxy

# Enable HAProxy to be managed via init script
sudo systemctl enable haproxy
