#!/usr/bin/env bash
# a Bash script that:

#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates
#itself when receiving a SIGQUIT or SIGTERM signal

file="/var/run/myscript.pid"

if [ ! -e $file ]
then
	touch $file
fi

pgrep -f 100-process_and_pid_file > $file

function sigquit()
{
	rm $file
	exit 0
}

function sigterm()
{
	echo "I hate the kill command"
	rm $file
	exit 0
}

trap "sigquit" SIGQUIT
trap "sigterm" SIGTERM
trap "echo Y U no love me?!" SIGINT

while true
do
	echo "To infinity and beyond"
done
