#!/usr/bin/env bash

touch /var/run/myscript.pid
pgrep -f 100-process_and_pid_file > /var/run/myscript.pid

function sigquit()
{
	rm /var/run/myscript.pid
	exit 0
}

function sigterm()
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit 0
}

while true
do
	trap "sigquit" SIGQUIT
	trap "sigterm" SIGTERM
	trap "echo Y U no love me?!" SIGINT
	echo "To infinity and beyond"
done
