#!/usr/bin/env bash
#a bash script that displays the content of the file /etc/passwd.

#The script only display:
#username
#user id
#Home directory path for the user


while read -r value
do
    echo "$value" | cut -d ':' -f 1,3,6
done < "/etc/passwd"
