#!/usr/bin/env bash
#display best school ten times and dislay
#"9" after the 9th interation

count=0

while [ $count -lt 10 ]
do
	if [ $count = 9 ]
	then
		echo Hi
	fi
	echo Best School
	((count += 1))
done
