#!/usr/bin/env bash
#this script displays the time for 12 hours and 59 minutes:

#display hours from 0 to 12
#display minutes from 1 to 59

hour=0


while [ ! $hour -gt 12 ]
do
	minute=1
	echo Hour: $hour
	while [ $minute -le 59 ]
	do
		echo $minute
		((minute += 1))
	done

	((hour += 1))
done
