#!/usr/bin/env bash
#a bash script that configures an Ubuntu server with the below requirements.

#Requirements:
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

echo -e "127.0.0.2\tlocalhost" > ~/hosts_new
echo -e "8.8.8.8\tfacebook.com" >> ~/hosts_new
cp -f ~/hosts_new /etc/hosts
rm ~/hosts_new
